name: 'Delete Branch Cache Action'
description: 'GitHub Actions to delete branch caches.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'trash-2'
  color: 'yellow'
inputs:
  repository:
    description: ''
    required: false
    default: ${{ github.repository }}
  ref:
    description: ''
    required: false
    default: ${{ github.ref }}
  key:
    description: ''
    required: false
    default: ''
  github-token:
    description: ''
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Delete branch caches
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        REF: ${{ inputs.ref }}
        KEY: ${{ inputs.key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -eu
        
        page=1
        per_page=100
        del_count=0

        while true
        do
          # Do not use query strings as it is necessary to URL encode if the key contains spaces
          res=$(curl -f \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPOSITORY/actions/caches?per_page=$per_page&page=$page")

          res_count=$(echo $res | tr -d '[:cntrl:]' | jq '.actions_caches | length')
          if [ $res_count -eq 0 ]; then break; fi

          targets=$(echo $res | tr -d '[:cntrl:]' | jq --arg ref "$REF" --arg key "$KEY" '.actions_caches[] | select(.ref == $ref) | select(.key | startswith($key))')
          echo "$targets"

          for id in $(echo $targets | jq '.id')
          do
            curl -f \
             -X DELETE \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: token $GITHUB_TOKEN" \
             "https://api.github.com/repos/$REPOSITORY/actions/caches/$id"
            ((del_count+=1))
          done

          ((page+=1))
        done
  
        echo "Delete $del_count caches."
