name: CI

on: push

jobs:
  ci:
    name: Use this action for check
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3
      - name: Use this action
        uses: ./
